OnlineBookStore.UI/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using OnlineBookStore.Common.Automapper;

namespace OnlineBookStore.UI.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();
        public IEnumerable<CartLine> Lines { get { return lineCollection; } }

        public void AddItem(BookModel book, int quantity)
        {
            CartLine line = lineCollection.Where(b => b.Book.Id == book.Id).FirstOrDefault();
            if (line == null)
            {
                lineCollection.Add(new CartLine { Book = book, Quantity = quantity });
            }
            else 
            {
                line.Quantity += quantity;
            }
        }
        public void RemoveItem(BookModel book)
        {
            lineCollection.RemoveAll(b => b.Book.Id == book.Id);
        }
        public decimal ComputeTotalValue()
        {
            return lineCollection.Sum(e => e.Book.Price * e.Quantity);
        }
        public void Clear()
        {
            lineCollection.Clear();
        }

        public OrderModel BindToOrder(ShippingDetailsModel shippingDetails)
        {
            OrderModel model = new OrderModel();
            model.OrderDate = DateTime.Now;
            model.ShippingDetails = shippingDetails;
            model.OrderItems = this.lineCollection.MapTo<OrderItemModel>();

            return model;
        }
    }
    
}

OnlineBookStore.UI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using OnlineBookStore.CustomProxy.IServices;
using OnlineBookStore.UI.Models;
using OnlineBookStore.UI.Const;
using OnlineBookStore.Common.Automapper;
using OnlineBookStore.CustomProxy.DataTransferObject;

namespace OnlineBookStore.UI.Controllers
{
    public class CartController : Controller
    {
        private readonly IOnlineBookStoreService _onlineBookStoreService;
        public CartController() { }
        public CartController(IOnlineBookStoreService onlineBookStoreService)
        {
            this._onlineBookStoreService = onlineBookStoreService;
        }
        public RedirectToRouteResult AddToCart(Cart cart, int id, string returnUrl)
        {
            BookModel book = _onlineBookStoreService.GetBookById(new GetBookByIdRequest() { BookId = id }).Book.MapTo<BookModel>();
            if (book.Id != 0)
            {
                cart.AddItem(book, 1);
            }
            return RedirectToAction(eAction.Index, new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int id, string returnUrl)
        {
            BookModel book = _onlineBookStoreService.GetBookById(new GetBookByIdRequest() { BookId = id }).Book.MapTo<BookModel>();
            if (book.Id != 0)
            {
                cart.RemoveItem(book);
            }
            return RedirectToAction(eAction.Index, new { returnUrl });
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            Debug.WriteLine(returnUrl);
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public PartialViewResult CartSummary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetailsModel());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetailsModel shippingDetail)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, but your cart is empty...");
            }
            if (ModelState.IsValid)
            {
                OrderModel model = cart.BindToOrder(shippingDetail);
                _onlineBookStoreService.SaveOrder(new SaveOrderRequest() { OrderVO = model.MapTo<OrderVO>() });
                cart.Clear();

                return View("Completed");
            }
            else
            {
                //throw new Exception("Test error");
                return View(new ShippingDetailsModel());
            }
        }
    }
}

OnlineBookStore.UI/Views/Cart/CartSummary.cshtml
@using OnlineBookStore.UI.Const
@model OnlineBookStore.UI.Models.Cart
<div id="cart">
    <span class="caption"><b>Your cart:</b> @Model.Lines.Sum(m => m.Quantity) book(s),
        @Model.ComputeTotalValue().ToString("c")
    </span>
    @Html.ActionLink("Checkout", eAction.Index, eController.Cart,
new { returnUrl = Request.Url.PathAndQuery }, null)
</div>

OnlineBookStore.UI/Views/Cart/Checkout.cshtml
@model OnlineBookStore.UI.Models.ShippingDetailsModel
@{
    ViewBag.Title = "Checkout";
}
<h2>
    Check out now</h2>
Give us shipping details:
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <table width="30%">
            <tbody>
                <tr>
                    <td>
                        <h3>Ship to:</h3>
                    </td>
                </tr>
                <tr>
                    <td>First: </td>
                    <td>@Html.EditorFor(x => x.FirstName)</td>
                </tr>
                <tr>
                    <td>Last: </td>
                    <td>@Html.EditorFor(x => x.LastName)</td>
                </tr>
                <tr>
                    <td>
                        <h3>Address:</h3>
                    </td>
                </tr>
                <tr>
                    <td>Line 1: </td>
                    <td>@Html.EditorFor(x => x.Line1)</td>
                </tr>
                <tr>
                    <td>Line 2:</td>
                    <td>@Html.EditorFor(x => x.Line2)</td>
                </tr>
                <tr>
                    <td>Line 3:</td>
                    <td>@Html.EditorFor(x => x.Line3)</td>
                </tr>
                <tr>
                    <td>City: </td>
                    <td>@Html.EditorFor(x => x.City)</td>
                </tr>
                <tr>
                    <td>Zip code: </td>
                    <td>@Html.EditorFor(x => x.Zip)</td>
                </tr>
                <tr>
                    <td>Country: </td>
                    <td>@Html.EditorFor(x => x.Country)</td>
                </tr>
                <tr>
                    <td align="center">
                        <input class="actionButtons" type="submit" value="Place order" />
                    </td>
                </tr>
            </tbody>
        </table>
}

OnlineBookStore.UI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Book Store: Order Submitted";
}
<h2>
    Thank you!</h2>
Your order has been placed. We will ship your package soon!

OnlineBookStore.UI/Views/Cart/Index.cshtml
@model OnlineBookStore.UI.Models.CartIndexViewModel
@{
    ViewBag.Title = "Your cart";
}
<h2>
    Your cart</h2>
<table width="90%" align="center">
    <thead>
        <tr>
            <th align="center">
                Quantity
            </th>
            <th align="left">
                Book
            </th>
            <th align="right">
                Price per item
            </th>
            <th align="right">
                Subtotal
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        { 
            <tr>
                <td align="center">
                    @line.Quantity
                </td>
                <td align="left">
                    @line.Book.Title
                </td>
                <td align="right">
                    @line.Book.Price
                </td>
                <td align="right">
                    @((line.Book.Price * line.Quantity).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    { 
                        @Html.Hidden("Id", line.Book.Id)
                        @Html.HiddenFor(m=>m.ReturnUrl)
                        <input class="actionButtons" type="submit" value="- Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">
                Total:
            </td>
            <td align="right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<p align="center" class="actionButtons">
    <a href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout now", OnlineBookStore.UI.Const.eAction.Checkout)
</p>